-- 向skins表添加卖出相关字段
ALTER TABLE skins ADD COLUMN is_sold TINYINT(1) DEFAULT 0 COMMENT '是否已卖出';
ALTER TABLE skins ADD COLUMN sold_price DECIMAL(10,2) DEFAULT 0 COMMENT '出售价格';
ALTER TABLE skins ADD COLUMN fee DECIMAL(10,2) DEFAULT 0 COMMENT '手续费';
ALTER TABLE skins ADD COLUMN sold_date DATE DEFAULT NULL COMMENT '卖出日期'; 